// Alert — Figma Component — Generated by figma-sync
// Execute via Figma Console MCP with the target file open

(async () => {
  const collections = await figma.variables.getLocalVariableCollectionsAsync();
  const colorCollection = collections.find(c => c.name === "Pylon/Colors");
  const colorCollectionId = colorCollection ? colorCollection.id : null;
  const radiiCollection = collections.find(c => c.name === "Pylon/Radii");

  // Helper: find a variable by name and collection
  async function findColorVar(name) {
    if (!colorCollectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("COLOR");
    return vars.find(v => v.name === name && v.variableCollectionId === colorCollectionId) || null;
  }

  async function findFloatVar(name, collectionId) {
    if (!collectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("FLOAT");
    return vars.find(v => v.name === name && v.variableCollectionId === collectionId) || null;
  }

  // Load font before creating text
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  await figma.loadFontAsync({ family: "Inter", style: "Medium" });
  await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });
  await figma.loadFontAsync({ family: "Inter", style: "Bold" });

  const components = [];

  // Type=Info
  {
    const node = figma.createComponent();
    node.name = "Type=Info";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.itemSpacing = 12;
    const radiusVar = await findFloatVar("radius/md", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const fillVar = await findColorVar("color-brand-light");
    if (fillVar) {
      const fillPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", fillVar);
      node.fills = [fillPaint];
    }
    const strokeVar = await findColorVar("color-brand");
    if (strokeVar) {
      const strokePaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", strokeVar);
      node.strokes = [strokePaint];
      node.strokeWeight = 1;
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Alert";
    const textVar = await findColorVar("color-brand-dark");
    if (textVar) {
      const textPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", textVar);
      text.fills = [textPaint];
    }
    node.appendChild(text);
    components.push(node);
  }

  // Type=Success
  {
    const node = figma.createComponent();
    node.name = "Type=Success";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.itemSpacing = 12;
    const radiusVar = await findFloatVar("radius/md", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const fillVar = await findColorVar("color-success-light");
    if (fillVar) {
      const fillPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", fillVar);
      node.fills = [fillPaint];
    }
    const strokeVar = await findColorVar("color-success");
    if (strokeVar) {
      const strokePaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", strokeVar);
      node.strokes = [strokePaint];
      node.strokeWeight = 1;
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Alert";
    const textVar = await findColorVar("color-success");
    if (textVar) {
      const textPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", textVar);
      text.fills = [textPaint];
    }
    node.appendChild(text);
    components.push(node);
  }

  // Type=Warning
  {
    const node = figma.createComponent();
    node.name = "Type=Warning";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.itemSpacing = 12;
    const radiusVar = await findFloatVar("radius/md", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const fillVar = await findColorVar("color-warning-light");
    if (fillVar) {
      const fillPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", fillVar);
      node.fills = [fillPaint];
    }
    const strokeVar = await findColorVar("color-warning");
    if (strokeVar) {
      const strokePaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", strokeVar);
      node.strokes = [strokePaint];
      node.strokeWeight = 1;
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Alert";
    const textVar = await findColorVar("color-warning");
    if (textVar) {
      const textPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", textVar);
      text.fills = [textPaint];
    }
    node.appendChild(text);
    components.push(node);
  }

  // Type=Error
  {
    const node = figma.createComponent();
    node.name = "Type=Error";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.itemSpacing = 12;
    const radiusVar = await findFloatVar("radius/md", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const fillVar = await findColorVar("color-error-light");
    if (fillVar) {
      const fillPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", fillVar);
      node.fills = [fillPaint];
    }
    const strokeVar = await findColorVar("color-error");
    if (strokeVar) {
      const strokePaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", strokeVar);
      node.strokes = [strokePaint];
      node.strokeWeight = 1;
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Alert";
    const textVar = await findColorVar("color-error");
    if (textVar) {
      const textPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", textVar);
      text.fills = [textPaint];
    }
    node.appendChild(text);
    components.push(node);
  }

  if (components.length > 1) {
    const componentSet = figma.combineAsVariants(components, figma.currentPage);
    componentSet.name = "Alert";

    // Auto-layout the component set for organization
    componentSet.layoutMode = "HORIZONTAL";
    componentSet.layoutWrap = "WRAP";
    componentSet.itemSpacing = 24;
    componentSet.counterAxisSpacing = 24;
    componentSet.paddingTop = 40;
    componentSet.paddingBottom = 40;
    componentSet.paddingLeft = 40;
    componentSet.paddingRight = 40;
    componentSet.primaryAxisSizingMode = "AUTO";
    componentSet.counterAxisSizingMode = "AUTO";
  } else if (components.length === 1) {
    components[0].name = "Alert";
  }

  figma.notify("✓ Alert: 4 variants created");
  figma.closePlugin();
})();
