// Avatar — Figma Component — Generated by figma-sync
// Execute via Figma Console MCP with the target file open

(async () => {
  const collections = await figma.variables.getLocalVariableCollectionsAsync();
  const colorCollection = collections.find(c => c.name === "Pylon/Colors");
  const colorCollectionId = colorCollection ? colorCollection.id : null;
  const radiiCollection = collections.find(c => c.name === "Pylon/Radii");

  // Helper: find a variable by name and collection
  async function findColorVar(name) {
    if (!colorCollectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("COLOR");
    return vars.find(v => v.name === name && v.variableCollectionId === colorCollectionId) || null;
  }

  async function findFloatVar(name, collectionId) {
    if (!collectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("FLOAT");
    return vars.find(v => v.name === name && v.variableCollectionId === collectionId) || null;
  }

  // Load font before creating text
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  await figma.loadFontAsync({ family: "Inter", style: "Medium" });
  await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });
  await figma.loadFontAsync({ family: "Inter", style: "Bold" });

  const components = [];

  // Size=SM
  {
    const node = figma.createComponent();
    node.name = "Size=SM";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.counterAxisAlignItems = "CENTER";
    node.primaryAxisAlignItems = "CENTER";
    node.counterAxisSizingMode = "FIXED";
    node.resize(node.width, 24);
    const radiusVar = await findFloatVar("radius/full", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 11;
    text.characters = "Avatar";
    node.appendChild(text);
    components.push(node);
  }

  // Size=MD
  {
    const node = figma.createComponent();
    node.name = "Size=MD";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.counterAxisAlignItems = "CENTER";
    node.primaryAxisAlignItems = "CENTER";
    node.counterAxisSizingMode = "FIXED";
    node.resize(node.width, 32);
    const radiusVar = await findFloatVar("radius/full", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Medium" };
    text.fontSize = 12;
    text.characters = "Avatar";
    node.appendChild(text);
    components.push(node);
  }

  // Size=LG
  {
    const node = figma.createComponent();
    node.name = "Size=LG";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.counterAxisAlignItems = "CENTER";
    node.primaryAxisAlignItems = "CENTER";
    node.counterAxisSizingMode = "FIXED";
    node.resize(node.width, 40);
    const radiusVar = await findFloatVar("radius/full", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 13;
    text.characters = "Avatar";
    node.appendChild(text);
    components.push(node);
  }

  // Size=XL
  {
    const node = figma.createComponent();
    node.name = "Size=XL";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.counterAxisAlignItems = "CENTER";
    node.primaryAxisAlignItems = "CENTER";
    node.counterAxisSizingMode = "FIXED";
    node.resize(node.width, 56);
    const radiusVar = await findFloatVar("radius/full", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Avatar";
    node.appendChild(text);
    components.push(node);
  }

  if (components.length > 1) {
    const componentSet = figma.combineAsVariants(components, figma.currentPage);
    componentSet.name = "Avatar";

    // Auto-layout the component set for organization
    componentSet.layoutMode = "HORIZONTAL";
    componentSet.layoutWrap = "WRAP";
    componentSet.itemSpacing = 24;
    componentSet.counterAxisSpacing = 24;
    componentSet.paddingTop = 40;
    componentSet.paddingBottom = 40;
    componentSet.paddingLeft = 40;
    componentSet.paddingRight = 40;
    componentSet.primaryAxisSizingMode = "AUTO";
    componentSet.counterAxisSizingMode = "AUTO";
  } else if (components.length === 1) {
    components[0].name = "Avatar";
  }

  figma.notify("✓ Avatar: 4 variants created");
  figma.closePlugin();
})();
