// Calendar — Figma Component — Generated by figma-sync
// Execute via Figma Console MCP with the target file open

(async () => {
  const collections = await figma.variables.getLocalVariableCollectionsAsync();
  const colorCollection = collections.find(c => c.name === "Pylon/Colors");
  const colorCollectionId = colorCollection ? colorCollection.id : null;
  const radiiCollection = collections.find(c => c.name === "Pylon/Radii");

  // Helper: find a variable by name and collection
  async function findColorVar(name) {
    if (!colorCollectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("COLOR");
    return vars.find(v => v.name === name && v.variableCollectionId === colorCollectionId) || null;
  }

  async function findFloatVar(name, collectionId) {
    if (!collectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("FLOAT");
    return vars.find(v => v.name === name && v.variableCollectionId === collectionId) || null;
  }

  // Load font before creating text
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  await figma.loadFontAsync({ family: "Inter", style: "Medium" });
  await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });
  await figma.loadFontAsync({ family: "Inter", style: "Bold" });

  const components = [];

  // Type=Outside, State=Default
  {
    const node = figma.createComponent();
    node.name = "Type=Outside, State=Default";
    node.layoutMode = "VERTICAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.itemSpacing = 8;
    const radiusVar = await findFloatVar("radius/lg", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Calendar";
    const textVar = await findColorVar("color-subtle");
    if (textVar) {
      const textPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", textVar);
      text.fills = [textPaint];
    }
    node.appendChild(text);
    components.push(node);
  }

  // Type=Outside, State=Hover
  {
    const node = figma.createComponent();
    node.name = "Type=Outside, State=Hover";
    node.layoutMode = "VERTICAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.itemSpacing = 8;
    const radiusVar = await findFloatVar("radius/lg", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Calendar";
    const textVar = await findColorVar("color-subtle");
    if (textVar) {
      const textPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", textVar);
      text.fills = [textPaint];
    }
    node.appendChild(text);
    components.push(node);
  }

  // Type=Outside, State=Pressed
  {
    const node = figma.createComponent();
    node.name = "Type=Outside, State=Pressed";
    node.layoutMode = "VERTICAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.itemSpacing = 8;
    const radiusVar = await findFloatVar("radius/lg", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Calendar";
    const textVar = await findColorVar("color-subtle");
    if (textVar) {
      const textPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", textVar);
      text.fills = [textPaint];
    }
    node.appendChild(text);
    components.push(node);
  }

  // Type=Outside, State=Selected
  {
    const node = figma.createComponent();
    node.name = "Type=Outside, State=Selected";
    node.layoutMode = "VERTICAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.itemSpacing = 8;
    const radiusVar = await findFloatVar("radius/lg", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Calendar";
    const textVar = await findColorVar("color-subtle");
    if (textVar) {
      const textPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", textVar);
      text.fills = [textPaint];
    }
    node.appendChild(text);
    components.push(node);
  }

  // Type=Outside, State=Disabled
  {
    const node = figma.createComponent();
    node.name = "Type=Outside, State=Disabled";
    node.layoutMode = "VERTICAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.itemSpacing = 8;
    const radiusVar = await findFloatVar("radius/lg", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Calendar";
    const textVar = await findColorVar("color-subtle");
    if (textVar) {
      const textPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", textVar);
      text.fills = [textPaint];
    }
    node.appendChild(text);
    node.opacity = 0.5;
    components.push(node);
  }

  // Type=Outside, State=Focused
  {
    const node = figma.createComponent();
    node.name = "Type=Outside, State=Focused";
    node.layoutMode = "VERTICAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.itemSpacing = 8;
    const radiusVar = await findFloatVar("radius/lg", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Calendar";
    const textVar = await findColorVar("color-subtle");
    if (textVar) {
      const textPaint = figma.variables.setBoundVariableForPaint({ type: "SOLID", color: {r:0,g:0,b:0} }, "color", textVar);
      text.fills = [textPaint];
    }
    node.appendChild(text);
    // Focus ring effect
    node.effects = [{
      type: "DROP_SHADOW",
      color: { r: 0.42, g: 0.545, b: 0.643, a: 1 },
      offset: { x: 0, y: 0 },
      radius: 0,
      spread: 4,
      visible: true,
      blendMode: "NORMAL"
    }];
    components.push(node);
  }

  if (components.length > 1) {
    const componentSet = figma.combineAsVariants(components, figma.currentPage);
    componentSet.name = "Calendar";

    // Auto-layout the component set for organization
    componentSet.layoutMode = "HORIZONTAL";
    componentSet.layoutWrap = "WRAP";
    componentSet.itemSpacing = 24;
    componentSet.counterAxisSpacing = 24;
    componentSet.paddingTop = 40;
    componentSet.paddingBottom = 40;
    componentSet.paddingLeft = 40;
    componentSet.paddingRight = 40;
    componentSet.primaryAxisSizingMode = "AUTO";
    componentSet.counterAxisSizingMode = "AUTO";
  } else if (components.length === 1) {
    components[0].name = "Calendar";
  }

  figma.notify("✓ Calendar: 6 variants created");
  figma.closePlugin();
})();
