// Checkbox — Figma Component — Generated by figma-sync
// Execute via Figma Console MCP with the target file open

(async () => {
  const collections = await figma.variables.getLocalVariableCollectionsAsync();
  const colorCollection = collections.find(c => c.name === "Pylon/Colors");
  const colorCollectionId = colorCollection ? colorCollection.id : null;
  const radiiCollection = collections.find(c => c.name === "Pylon/Radii");

  // Helper: find a variable by name and collection
  async function findColorVar(name) {
    if (!colorCollectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("COLOR");
    return vars.find(v => v.name === name && v.variableCollectionId === colorCollectionId) || null;
  }

  async function findFloatVar(name, collectionId) {
    if (!collectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("FLOAT");
    return vars.find(v => v.name === name && v.variableCollectionId === collectionId) || null;
  }

  // Load font before creating text
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  await figma.loadFontAsync({ family: "Inter", style: "Medium" });
  await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });
  await figma.loadFontAsync({ family: "Inter", style: "Bold" });

  const components = [];

  // State=Default
  {
    const node = figma.createComponent();
    node.name = "State=Default";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.counterAxisAlignItems = "CENTER";
    node.itemSpacing = 8;
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Checkbox";
    node.appendChild(text);
    components.push(node);
  }

  // State=Hover
  {
    const node = figma.createComponent();
    node.name = "State=Hover";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.counterAxisAlignItems = "CENTER";
    node.itemSpacing = 8;
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Checkbox";
    node.appendChild(text);
    components.push(node);
  }

  // State=Selected
  {
    const node = figma.createComponent();
    node.name = "State=Selected";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.counterAxisAlignItems = "CENTER";
    node.itemSpacing = 8;
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Checkbox";
    node.appendChild(text);
    components.push(node);
  }

  // State=Disabled
  {
    const node = figma.createComponent();
    node.name = "State=Disabled";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.counterAxisAlignItems = "CENTER";
    node.itemSpacing = 8;
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Checkbox";
    node.appendChild(text);
    node.opacity = 0.5;
    components.push(node);
  }

  // State=Focused
  {
    const node = figma.createComponent();
    node.name = "State=Focused";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.counterAxisAlignItems = "CENTER";
    node.itemSpacing = 8;
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Checkbox";
    node.appendChild(text);
    // Focus ring effect
    node.effects = [{
      type: "DROP_SHADOW",
      color: { r: 0.42, g: 0.545, b: 0.643, a: 1 },
      offset: { x: 0, y: 0 },
      radius: 0,
      spread: 4,
      visible: true,
      blendMode: "NORMAL"
    }];
    components.push(node);
  }

  // State=Invalid
  {
    const node = figma.createComponent();
    node.name = "State=Invalid";
    node.layoutMode = "HORIZONTAL";
    node.primaryAxisSizingMode = "AUTO";
    node.counterAxisSizingMode = "AUTO";
    node.counterAxisAlignItems = "CENTER";
    node.itemSpacing = 8;
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 15;
    text.characters = "Checkbox";
    node.appendChild(text);
    components.push(node);
  }

  if (components.length > 1) {
    const componentSet = figma.combineAsVariants(components, figma.currentPage);
    componentSet.name = "Checkbox";

    // Auto-layout the component set for organization
    componentSet.layoutMode = "HORIZONTAL";
    componentSet.layoutWrap = "WRAP";
    componentSet.itemSpacing = 24;
    componentSet.counterAxisSpacing = 24;
    componentSet.paddingTop = 40;
    componentSet.paddingBottom = 40;
    componentSet.paddingLeft = 40;
    componentSet.paddingRight = 40;
    componentSet.primaryAxisSizingMode = "AUTO";
    componentSet.counterAxisSizingMode = "AUTO";
  } else if (components.length === 1) {
    components[0].name = "Checkbox";
  }

  figma.notify("✓ Checkbox: 6 variants created");
  figma.closePlugin();
})();
