// Input — Figma Component — Generated by figma-sync
// Execute via Figma Console MCP with the target file open

(async () => {
  const collections = await figma.variables.getLocalVariableCollectionsAsync();
  const colorCollection = collections.find(c => c.name === "Pylon/Colors");
  const colorCollectionId = colorCollection ? colorCollection.id : null;
  const radiiCollection = collections.find(c => c.name === "Pylon/Radii");

  // Helper: find a variable by name and collection
  async function findColorVar(name) {
    if (!colorCollectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("COLOR");
    return vars.find(v => v.name === name && v.variableCollectionId === colorCollectionId) || null;
  }

  async function findFloatVar(name, collectionId) {
    if (!collectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("FLOAT");
    return vars.find(v => v.name === name && v.variableCollectionId === collectionId) || null;
  }

  // Load font before creating text
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  await figma.loadFontAsync({ family: "Inter", style: "Medium" });
  await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });
  await figma.loadFontAsync({ family: "Inter", style: "Bold" });

  const components = [];

  // Size=SM
  {
    const node = figma.createComponent();
    node.name = "Size=SM";
    node.counterAxisSizingMode = "FIXED";
    node.resize(node.width, 32);
    node.paddingTop = 4;
    node.paddingBottom = 4;
    node.paddingLeft = 8;
    node.paddingRight = 8;
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 13;
    text.characters = "Input";
    node.appendChild(text);
    components.push(node);
  }

  // Size=LG
  {
    const node = figma.createComponent();
    node.name = "Size=LG";
    node.counterAxisSizingMode = "FIXED";
    node.resize(node.width, 44);
    node.paddingTop = 12;
    node.paddingBottom = 12;
    node.paddingLeft = 16;
    node.paddingRight = 16;
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.fontSize = 17;
    text.characters = "Input";
    node.appendChild(text);
    components.push(node);
  }

  if (components.length > 1) {
    const componentSet = figma.combineAsVariants(components, figma.currentPage);
    componentSet.name = "Input";

    // Auto-layout the component set for organization
    componentSet.layoutMode = "HORIZONTAL";
    componentSet.layoutWrap = "WRAP";
    componentSet.itemSpacing = 24;
    componentSet.counterAxisSpacing = 24;
    componentSet.paddingTop = 40;
    componentSet.paddingBottom = 40;
    componentSet.paddingLeft = 40;
    componentSet.paddingRight = 40;
    componentSet.primaryAxisSizingMode = "AUTO";
    componentSet.counterAxisSizingMode = "AUTO";
  } else if (components.length === 1) {
    components[0].name = "Input";
  }

  figma.notify("✓ Input: 2 variants created");
  figma.closePlugin();
})();
