// Modal — Figma Component — Generated by figma-sync
// Execute via Figma Console MCP with the target file open

(async () => {
  const collections = await figma.variables.getLocalVariableCollectionsAsync();
  const colorCollection = collections.find(c => c.name === "Pylon/Colors");
  const colorCollectionId = colorCollection ? colorCollection.id : null;
  const radiiCollection = collections.find(c => c.name === "Pylon/Radii");

  // Helper: find a variable by name and collection
  async function findColorVar(name) {
    if (!colorCollectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("COLOR");
    return vars.find(v => v.name === name && v.variableCollectionId === colorCollectionId) || null;
  }

  async function findFloatVar(name, collectionId) {
    if (!collectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("FLOAT");
    return vars.find(v => v.name === name && v.variableCollectionId === collectionId) || null;
  }

  // Load font before creating text
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  await figma.loadFontAsync({ family: "Inter", style: "Medium" });
  await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });
  await figma.loadFontAsync({ family: "Inter", style: "Bold" });

  const components = [];

  // Size=SM, State=Default
  {
    const node = figma.createComponent();
    node.name = "Size=SM, State=Default";
    const radiusVar = await findFloatVar("radius/xl", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Modal";
    node.appendChild(text);
    components.push(node);
  }

  // Size=SM, State=Focused
  {
    const node = figma.createComponent();
    node.name = "Size=SM, State=Focused";
    const radiusVar = await findFloatVar("radius/xl", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Modal";
    node.appendChild(text);
    // Focus ring effect
    node.effects = [{
      type: "DROP_SHADOW",
      color: { r: 0.42, g: 0.545, b: 0.643, a: 1 },
      offset: { x: 0, y: 0 },
      radius: 0,
      spread: 4,
      visible: true,
      blendMode: "NORMAL"
    }];
    components.push(node);
  }

  // Size=SM, State=Entering
  {
    const node = figma.createComponent();
    node.name = "Size=SM, State=Entering";
    const radiusVar = await findFloatVar("radius/xl", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Modal";
    node.appendChild(text);
    components.push(node);
  }

  // Size=SM, State=Exiting
  {
    const node = figma.createComponent();
    node.name = "Size=SM, State=Exiting";
    const radiusVar = await findFloatVar("radius/xl", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Modal";
    node.appendChild(text);
    components.push(node);
  }

  // Size=LG, State=Default
  {
    const node = figma.createComponent();
    node.name = "Size=LG, State=Default";
    const radiusVar = await findFloatVar("radius/xl", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Modal";
    node.appendChild(text);
    components.push(node);
  }

  // Size=LG, State=Focused
  {
    const node = figma.createComponent();
    node.name = "Size=LG, State=Focused";
    const radiusVar = await findFloatVar("radius/xl", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Modal";
    node.appendChild(text);
    // Focus ring effect
    node.effects = [{
      type: "DROP_SHADOW",
      color: { r: 0.42, g: 0.545, b: 0.643, a: 1 },
      offset: { x: 0, y: 0 },
      radius: 0,
      spread: 4,
      visible: true,
      blendMode: "NORMAL"
    }];
    components.push(node);
  }

  // Size=LG, State=Entering
  {
    const node = figma.createComponent();
    node.name = "Size=LG, State=Entering";
    const radiusVar = await findFloatVar("radius/xl", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Modal";
    node.appendChild(text);
    components.push(node);
  }

  // Size=LG, State=Exiting
  {
    const node = figma.createComponent();
    node.name = "Size=LG, State=Exiting";
    const radiusVar = await findFloatVar("radius/xl", radiiCollection?.id);
    if (radiusVar) {
      node.setBoundVariable("topLeftRadius", radiusVar);
      node.setBoundVariable("topRightRadius", radiusVar);
      node.setBoundVariable("bottomLeftRadius", radiusVar);
      node.setBoundVariable("bottomRightRadius", radiusVar);
    }
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Modal";
    node.appendChild(text);
    components.push(node);
  }

  if (components.length > 1) {
    const componentSet = figma.combineAsVariants(components, figma.currentPage);
    componentSet.name = "Modal";

    // Auto-layout the component set for organization
    componentSet.layoutMode = "HORIZONTAL";
    componentSet.layoutWrap = "WRAP";
    componentSet.itemSpacing = 24;
    componentSet.counterAxisSpacing = 24;
    componentSet.paddingTop = 40;
    componentSet.paddingBottom = 40;
    componentSet.paddingLeft = 40;
    componentSet.paddingRight = 40;
    componentSet.primaryAxisSizingMode = "AUTO";
    componentSet.counterAxisSizingMode = "AUTO";
  } else if (components.length === 1) {
    components[0].name = "Modal";
  }

  figma.notify("✓ Modal: 8 variants created");
  figma.closePlugin();
})();
