// Scroll Area — Figma Component — Generated by figma-sync
// Execute via Figma Console MCP with the target file open

(async () => {
  const collections = await figma.variables.getLocalVariableCollectionsAsync();
  const colorCollection = collections.find(c => c.name === "Pylon/Colors");
  const colorCollectionId = colorCollection ? colorCollection.id : null;
  const radiiCollection = collections.find(c => c.name === "Pylon/Radii");

  // Helper: find a variable by name and collection
  async function findColorVar(name) {
    if (!colorCollectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("COLOR");
    return vars.find(v => v.name === name && v.variableCollectionId === colorCollectionId) || null;
  }

  async function findFloatVar(name, collectionId) {
    if (!collectionId) return null;
    const vars = await figma.variables.getLocalVariablesAsync("FLOAT");
    return vars.find(v => v.name === name && v.variableCollectionId === collectionId) || null;
  }

  // Load font before creating text
  await figma.loadFontAsync({ family: "Inter", style: "Regular" });
  await figma.loadFontAsync({ family: "Inter", style: "Medium" });
  await figma.loadFontAsync({ family: "Inter", style: "Semi Bold" });
  await figma.loadFontAsync({ family: "Inter", style: "Bold" });

  const components = [];

  // State=Default
  {
    const node = figma.createComponent();
    node.name = "State=Default";
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Scroll Area";
    node.appendChild(text);
    components.push(node);
  }

  // State=Hover
  {
    const node = figma.createComponent();
    node.name = "State=Hover";
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Scroll Area";
    node.appendChild(text);
    components.push(node);
  }

  // State=Pressed
  {
    const node = figma.createComponent();
    node.name = "State=Pressed";
    const text = figma.createText();
    text.fontName = { family: "Inter", style: "Regular" };
    text.characters = "Scroll Area";
    node.appendChild(text);
    components.push(node);
  }

  if (components.length > 1) {
    const componentSet = figma.combineAsVariants(components, figma.currentPage);
    componentSet.name = "Scroll Area";

    // Auto-layout the component set for organization
    componentSet.layoutMode = "HORIZONTAL";
    componentSet.layoutWrap = "WRAP";
    componentSet.itemSpacing = 24;
    componentSet.counterAxisSpacing = 24;
    componentSet.paddingTop = 40;
    componentSet.paddingBottom = 40;
    componentSet.paddingLeft = 40;
    componentSet.paddingRight = 40;
    componentSet.primaryAxisSizingMode = "AUTO";
    componentSet.counterAxisSizingMode = "AUTO";
  } else if (components.length === 1) {
    components[0].name = "Scroll Area";
  }

  figma.notify("✓ Scroll Area: 3 variants created");
  figma.closePlugin();
})();
